// <auto-generated />
namespace CIS174ErikJohnsonOfficial.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropUserModifyPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropUserModifyPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201902202316393_DropUserModifyPerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
